### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by hasib-rashid** [SpiderMath/Discord-Multipurpose#7]
~~Definitely didnt make an issue to test my readme~~

**Comment by hasib-rashid** [comment]
Another test cuz i suck at code

**Comment by SpiderMath** [comment]
As of now, no it isn't. I am still waiting for [Discord.js](https://npmjs.com/package/discord.js) v13 to release since it is currently unstable. That is why the project has been put on Temporary Hold.

**Comment by SpiderMath** [comment]
As you might already know, Discord.js is the main library this package is building on, so working without the update will only ruin everything built without it.

**Comment by hasib-rashid** [comment]
true

**Comment by SpiderMath** [comment]
Discord.js V13 has been announced and thus the project is to be restarted soon.
